#
# Module manifest for module 'PSCoveralls'
#
# Generated by: Matthew Kelly (Badgerati)
#
# Generated on: 29/08/2019
#

@{
    # Script module or binary module file associated with this manifest.
    RootModule = 'PSCoveralls.psm1'

    # Version number of this module.
    ModuleVersion = '1.0.0'

    # ID used to uniquely identify this module
    GUID = 'b309b7ed-ae95-40d5-919c-4366f6196ce6'

    # Author of this module
    Author = 'Matthew Kelly (Badgerati)'

    # Copyright statement for this module
    Copyright = 'Copyright (c) 2019 Matthew Kelly (Badgerati), licensed under the MIT License.'

    # Description of the functionality provided by this module
    Description = 'PowerShell module to publish Pester Code Coverage reports to Coveralls.io'

    # Minimum version of the Windows PowerShell engine required by this module
    PowerShellVersion = '3.0'

    # Functions to export from this module
    FunctionsToExport = @('Publish-CoverallsReport', 'New-CoverallsReport', 'Get-CoverallsPercentage')

    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData = @{
        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            Tags = @('powershell', 'tests', 'coverage', 'coveralls')

            # A URL to the license for this module.
            LicenseUri = 'https://raw.githubusercontent.com/Badgerati/PSCoveralls/master/LICENSE.txt'

            # A URL to the main website for this project.
            ProjectUri = 'https://github.com/Badgerati/PSCoveralls'

        }
    }
}